services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - "443:443"
    command:
      # Enable Docker provider. Automatically discover services. See labels under frontend and backend containers.
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Define entrypoints for HTTPS
      - --entrypoints.websecure.address=:443
      # Static TLS configuration from /certs/dynamic.yml
      - --providers.file.filename=/certs/dynamic.yml
    volumes:
      # Mount Docker socket as read-only to allow Traefik to discover services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Cloudflare Certs
      - ./certs/:/certs/:ro
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  frontend:
    container_name: frontend
    image: ghcr.io/ikozay/trackmydegree-frontend:latest
    restart: always
    expose:
      - "3000"
    volumes:
      - ./secrets/frontend.env:/app/.env:ro
    networks:
      - app-network
    depends_on:
      - backend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`stg.trackmydegree.ca`) && !PathPrefix(`/auth`) && !PathPrefix(`/courses`) && !PathPrefix(`/degree`) && !PathPrefix(`/timeline`) && !PathPrefix(`/coursepool`) && !PathPrefix(`/users`) && !PathPrefix(`/admin`) && !PathPrefix(`/feedback`) && !PathPrefix(`/session`) && !PathPrefix(`/section`) && !PathPrefix(`/upload`) && !PathPrefix(`/api-docs`) && !PathPrefix(`/openapi.json`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  backend:
    container_name: backend
    image: ghcr.io/ikozay/trackmydegree-backend:latest
    restart: always
    expose:
      - "8000"
    volumes:
      - ./backups:/var/backups
    env_file:
      - ./secrets/backend.env
    networks:
      - app-network
    depends_on:
      - redis
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`stg.trackmydegree.ca`) && (PathPrefix(`/auth`) || PathPrefix(`/courses`) || PathPrefix(`/degree`) || PathPrefix(`/timeline`) || PathPrefix(`/coursepool`) || PathPrefix(`/users`) || PathPrefix(`/admin`) || PathPrefix(`/feedback`) || PathPrefix(`/session`) || PathPrefix(`/section`) || PathPrefix(`/upload`) || PathPrefix(`/api-docs`) || PathPrefix(`/openapi.json`))"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    volumes:
      - mongodb-data:/data/db
    env_file:
      # To provide MONGO_INITDB_ROOT_USERNAME, MONGO_INITDB_ROOT_PASSWORD and MONGO_INITDB_DATABASE
      - ./secrets/mongo.env
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    labels:
      - "traefik.enable=false"
  
  # Add Watchtower for automatic updates
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60  # check every minute
    environment:
      - WATCHTOWER_CLEANUP=true  # remove old images
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_DEBUG=false
      - WATCHTOWER_REGISTRY_AUTH=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  mongodb-data: