services:
  traefik:
    container_name: traefik
    image: traefik:v3
    restart: always
    ports:
      - "443:443"
    command:
      # Enable Docker provider. Automatically discover services. See labels under frontend and backend containers.
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Define entrypoints for HTTPS
      - --entrypoints.websecure.address=:443
      # Static TLS and Auth configuration from /traefik/dynamic.stg.yml
      - --providers.file.filename=/traefik/dynamic.stg.yml
    volumes:
      # Mount Docker socket as read-only to allow Traefik to discover services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Traefik Auth and TLS configuration
      - ./traefik/:/traefik/:ro
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  frontend:
    container_name: frontend
    image: ghcr.io/ikozay/trackmydegree-frontend:latest
    restart: always
    expose:
      - "4173"
    environment:
      - VITE_NODE_ENV=staging
      - VITE_API_SERVER=https://stg.trackmydegree.ca/api
      - VITE_POSTHOG_KEY=phc_F2YuzjGC9JBSTL3xgdrH2OKv9u8voG2e7XSYiAP7F5z
      - VITE_POSTHOG_HOST=https://us.i.posthog.com
    networks:
      - app-network
    depends_on:
      - backend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`stg.${DOMAIN}`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.middlewares=basic-auth@file"
      - "traefik.http.services.frontend.loadbalancer.server.port=4173"

  backend:
    container_name: backend
    image: ghcr.io/ikozay/trackmydegree-backend:latest
    restart: always
    expose:
      - "8000"
    volumes:
      - ./backups:/var/backups
    env_file:
      - ./secrets/backend.env
    networks:
      - app-network
    depends_on:
      - redis
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`stg.${DOMAIN}`) && (PathPrefix(`/api`))"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.middlewares=basic-auth@file"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  mongodb:
    container_name: mongodb
    image: mongo:8.2
    restart: always
    expose:
      - "27017"
    volumes:
      - mongodb-data:/data/db
    env_file:
      # To provide MONGO_INITDB_ROOT_USERNAME, MONGO_INITDB_ROOT_PASSWORD and MONGO_INITDB_DATABASE
      - ./secrets/mongo.env
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  redis:
    container_name: redis
    image: redis:8.2
    restart: always
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    labels:
      - "traefik.enable=false"
  
  # Add Watchtower for automatic updates
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300  # check every 5 minutes
    environment:
      - WATCHTOWER_CLEANUP=true  # remove old images
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_DEBUG=false
      - WATCHTOWER_REGISTRY_AUTH=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  mongodb-data: